/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.controlador.ControladorFactura;
import ec.edu.ups.controlador.ControladorSitio;
import ec.edu.ups.modelo.Cliente;
import ec.edu.ups.modelo.Factura;
import ec.edu.ups.modelo.Sitio;
import java.text.DecimalFormat;
import java.time.Duration;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import java.util.concurrent.TimeUnit;
import javax.swing.JOptionPane;

/**
 *
 * @author NANCY
 */
public class VentanaCobro extends javax.swing.JInternalFrame {

    private ControladorSitio controladorSitio;
    private ControladorFactura controladorFactura;
    private LocalDateTime local;
    
    /**
     * Creates new form VentanaCobro
     * @param controladorFactura
     * @param controladorSitio
     */
    public VentanaCobro(ControladorFactura controladorFactura,ControladorSitio controladorSitio) {
        initComponents();
        this.controladorFactura=controladorFactura;
        this.controladorSitio=controladorSitio;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        txtSitio = new javax.swing.JTextField();
        cbxDescuento = new javax.swing.JComboBox<>();
        txtTotal = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnCobrar = new javax.swing.JButton();
        btnDescuento = new javax.swing.JButton();
        JDateEntarda = new com.toedter.calendar.JDateChooser();
        JDateSalida = new com.toedter.calendar.JDateChooser();

        setClosable(true);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Factura ");

        jLabel2.setText("Numero de Tiket");

        jLabel3.setText("Fecha de Entrada");

        jLabel4.setText("Fecha de Salida");

        jLabel5.setText("Nombre Cliente");

        jLabel6.setText("Apellido");

        jLabel7.setText("Cedula");

        jLabel8.setText("Sitio de Parqueo");

        jLabel9.setText("Descuento");

        jLabel10.setText("Total  a Pagar");

        txtNombre.setEditable(false);
        txtNombre.setBackground(new java.awt.Color(255, 255, 204));

        txtApellido.setEditable(false);
        txtApellido.setBackground(new java.awt.Color(255, 255, 204));

        txtCedula.setEditable(false);
        txtCedula.setBackground(new java.awt.Color(255, 255, 204));

        txtSitio.setEditable(false);
        txtSitio.setBackground(new java.awt.Color(255, 255, 204));

        cbxDescuento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "5", "10", "15", "20", "25" }));

        txtTotal.setEditable(false);
        txtTotal.setBackground(new java.awt.Color(255, 255, 204));

        btnBuscar.setText("Buscar Tiket");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnCobrar.setText("Cobrar");
        btnCobrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCobrarActionPerformed(evt);
            }
        });

        btnDescuento.setText("Aplicar Descuento");
        btnDescuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescuentoActionPerformed(evt);
            }
        });

        JDateEntarda.setDateFormatString("y MMM d HH:mm:ss");

        JDateSalida.setDateFormatString("y MMM d HH:mm:ss");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnCobrar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnDescuento))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNombre)
                                    .addComponent(txtApellido)
                                    .addComponent(txtCedula)
                                    .addComponent(txtSitio)
                                    .addComponent(cbxDescuento, 0, 200, Short.MAX_VALUE)
                                    .addComponent(txtTotal)
                                    .addComponent(JDateEntarda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(JDateSalida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3))
                            .addComponent(JDateEntarda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4))
                    .addComponent(JDateSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtSitio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cbxDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar)
                    .addComponent(btnCobrar)
                    .addComponent(btnDescuento))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        int numero=Integer.parseInt(txtNumero.getText());
        Factura fac= new Factura(numero);
        Factura factura= controladorFactura.read(fac);
        String estado= factura.getEstado();
        if(factura!= null){
            if(estado.equals("deuda")){

                Calendar fechaSalida= Calendar.getInstance();
                JDateSalida.setCalendar(fechaSalida);
                Cliente cliente = factura.getCliente();
                Sitio sitio= factura.getSitio();
                JDateEntarda.setCalendar(factura.getFechaYHoraDeIngreso());
                txtNombre.setText(cliente.getNombre());
                txtApellido.setText(cliente.getApellido());
                txtCedula.setText(cliente.getCedula());
                txtSitio.setText(sitio.getNumero());
                
                long DiferenciaMiliSegundos= Math.abs(JDateSalida.getCalendar().getTimeInMillis()-JDateEntarda.getCalendar().getTimeInMillis());
                long minutos=TimeUnit.MILLISECONDS.toMinutes(DiferenciaMiliSegundos);
                System.out.println(minutos);
                
                if(minutos<=30){
                    txtTotal.setText(String.valueOf(0.60));
                }else{
                    if(minutos<=60){
                        txtTotal.setText(String.valueOf(1));
                    }else{
                        int diferencia= (int) (minutos-60);
                        double valorPagar= ((diferencia*0.02)+1);
                        txtTotal.setText(String.valueOf(valorPagar));
                    }
                }
                //           DateTimeFormatter formato = DateTimeFormatter.ofPattern("yyyy-mm-dd HH:mm");
                /*LocalDate d1 = LocalDate.parse(FechaEntrada.toString(), DateTimeFormatter.ISO_LOCAL_DATE_TIME);
                LocalDate d2 = LocalDate.parse(local.toString(), DateTimeFormatter.ISO_LOCAL_DATE_TIME);
                Duration diff = Duration.between(d1.atStartOfDay(), d2.atStartOfDay());
                System.out.println(d1);
                System.out.println(d2);
                System.out.println(diff);
                long diffDays = diff.toMillis();
                System.out.println(diffDays);
                //txtTotal.setText(String.valueOf(diffDays));
                if (diffDays <= 10) {
                    txtTotal.setText(String.valueOf(0.25));
                } else if (diffDays > 10) {
                    int calcularTotal = (int) diffDays / 10;
                    calcularTotal = (int) (calcularTotal * 0.25);
                    txtTotal.setText(String.valueOf(calcularTotal));
                }*/   
            }else{
                JOptionPane.showMessageDialog(this, "El Tiket Buscado ya ah sido cobrado");
            }
        }else{
            JOptionPane.showMessageDialog(this, "Tiket no encontrado");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnDescuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescuentoActionPerformed
       int decsuento= Integer.parseInt(cbxDescuento.getSelectedItem().toString());
       System.out.println(decsuento);
       double descontar = decsuento*0.01;
       System.out.println(descontar);
       float cantidad=(float) Double.parseDouble(txtTotal.getText());
       System.out.println(cantidad);
       float operacion =(float) (cantidad*descontar);
       System.out.println(operacion);
       double hacerDescuento=cantidad-operacion;
        System.out.println(hacerDescuento);
       //DecimalFormat df = new DecimalFormat("0.00");
       //String formato= df.format(hacerDescuento);
       txtTotal.setText(String.valueOf(String.format("%.2f", hacerDescuento)));
       //txtTotal.setText(String.valueOf(hacerDescuento));   
    }//GEN-LAST:event_btnDescuentoActionPerformed

    private void btnCobrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCobrarActionPerformed
        int numero=Integer.parseInt(txtNumero.getText());
        Factura fac= new Factura(numero);
        Factura factura= controladorFactura.read(fac);
        txtTotal.getText();
        Cliente cliente = factura.getCliente();
        Sitio sitio= factura.getSitio();
        //float cantidad=(float) Double.parseDouble(txtTotal.getText());
        
        Sitio sitios= new Sitio(txtSitio.getText(), "Libre", null);
        controladorSitio.update(sitios);
        
        String total= txtTotal.getText().replace(",", ".");
        double totalDouble=Double.parseDouble(total);
        
        Factura factura1= new Factura(numero, factura.getFechaYHoraDeIngreso(), JDateSalida.getCalendar(), "Pagado", totalDouble, cliente, sitio);
        controladorFactura.update(factura1);
        JOptionPane.showMessageDialog(this, "Gracias vuelva pronto");
        limpira();
        this.setVisible(false);
    }//GEN-LAST:event_btnCobrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser JDateEntarda;
    private com.toedter.calendar.JDateChooser JDateSalida;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCobrar;
    private javax.swing.JButton btnDescuento;
    private javax.swing.JComboBox<String> cbxDescuento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtSitio;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables

    private void limpira() {
        txtNumero.setText("");
        JDateEntarda.setDateFormatString("");
        JDateSalida.setDateFormatString("");
        txtNombre.setText("");
        txtApellido.setText("");
        txtCedula.setText("");
        txtSitio.setText("");
        cbxDescuento.setSelectedIndex(0);
        txtTotal.setText("");
    }
}
