/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.controlador.ControladorCliente;
import ec.edu.ups.controlador.ControladorFactura;
import ec.edu.ups.controlador.ControladorSitio;
import ec.edu.ups.controlador.ControladorVehiculo;
import ec.edu.ups.modelo.Cliente;
import ec.edu.ups.modelo.Factura;
import ec.edu.ups.modelo.Sitio;
import ec.edu.ups.modelo.Vehiculo;
import java.time.LocalDateTime;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author NANCY
 */
public class VentanaTiketIngreso extends javax.swing.JInternalFrame {

    private ControladorCliente controladorCliente;
    private ControladorVehiculo controladorVehiculo;
    private ControladorSitio controladorSitio;
    private ControladorFactura controladorFactura;
    private String numero;
    private LocalDateTime local;
    /**
     * Creates new form VentanaTiketIngreso
     * @param controladorFactura
     * @param controladorSitio
     * @param controladorVehiculo
     * @param controladorCliente
     */
    public VentanaTiketIngreso(ControladorFactura controladorFactura,ControladorSitio controladorSitio,ControladorVehiculo controladorVehiculo,ControladorCliente controladorCliente) {
        initComponents();
        
        this.controladorFactura= controladorFactura;
        this.controladorSitio= controladorSitio;
        this.controladorVehiculo=controladorVehiculo;
        this.controladorCliente= controladorCliente;
 
    }

    public int cargarCodigo() {
        int cod = controladorFactura.cargarCodigo();
        //txtCodigo.setText(String.valueOf(cod));
        return cod;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }

    public void CrearFactura(){
        int codigo= cargarCodigo();
        local = LocalDateTime.now();
        String estado="deuda";
        
        Calendar fechaIngreso = Calendar.getInstance();
        Sitio sit= new Sitio(numero);
        Sitio sitio=this.controladorSitio.read(sit);
        Vehiculo vehiculo = sitio.getVehiculo();
        Cliente cliente=vehiculo.getCliente();
        
        Factura factura=new Factura(codigo, fechaIngreso, estado, cliente, sitio);
        boolean respuesta= controladorFactura.create(factura);
        
        String datos = "Tiket numero: "+codigo+"\nFecha y hora de ingreso: "+fechaIngreso.getTime()+"\nCliente: " +cliente.getNombre()+" "+cliente.getApellido()+"\nCedula: "+cliente.getCedula()+"\nPlaca vehiculo: "+vehiculo.getPlaca()+"\nMarca: "+vehiculo.getMarca()+"\nModelo: "+vehiculo.getModelo()+"\nNumero sitio parqueado: "+sitio.getNumero();
        txtDatos.setText(datos);
        JOptionPane.showMessageDialog(this, "Operación : " + respuesta);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtDatos = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        txtDatos.setEditable(false);
        txtDatos.setColumns(20);
        txtDatos.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        txtDatos.setRows(5);
        jScrollPane1.setViewportView(txtDatos);

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(243, 243, 243))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        CrearFactura();
    }//GEN-LAST:event_formInternalFrameActivated


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtDatos;
    // End of variables declaration//GEN-END:variables
}
