/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.controlador.ControladorCliente;
import ec.edu.ups.controlador.ControladorContrato;
import ec.edu.ups.controlador.ControladorSitio;
import ec.edu.ups.controlador.ControladorVehiculo;
import ec.edu.ups.modelo.Cliente;
import ec.edu.ups.modelo.Contrato;
import ec.edu.ups.modelo.Sitio;
import ec.edu.ups.modelo.Vehiculo;
import java.util.Calendar;
import java.util.Date;
import java.util.concurrent.TimeUnit;
import javax.swing.JOptionPane;

/**
 *
 * @author NANCY
 */
public class VentanaContrato extends javax.swing.JInternalFrame {

    private ControladorContrato controladorContrato;
    private ControladorCliente controladorCliente;
    private ControladorVehiculo controladorVehiculo;
    private ControladorSitio controladorSitio;
    private VentanaPrincipal ventanaPrincipal;
    private VentanaGestionVehiculo ventanaGestionVehiculo;
    private VentanaTiketIngreso ventanaTiketIngreso;
    /**
     * Creates new form VentanaContrato
     * @param controladorContrato
     * @param controladorSitio
     * @param controladorVehiculo
     * @param controladorCliente
     * @param ventanaPrincipal
     * @param ventanaGestionVehiculo
     */
    public VentanaContrato(ControladorContrato controladorContrato,ControladorSitio controladorSitio,ControladorVehiculo controladorVehiculo,ControladorCliente controladorCliente , VentanaPrincipal ventanaPrincipal, VentanaGestionVehiculo ventanaGestionVehiculo) {
        initComponents();
        
        this.controladorContrato=controladorContrato;
        this.controladorSitio=controladorSitio;
        this.controladorVehiculo=controladorVehiculo;
        this.controladorCliente= controladorCliente;
        this.ventanaPrincipal=ventanaPrincipal;
        this.ventanaGestionVehiculo=ventanaGestionVehiculo;
    }

    public void cargarCodigo() {
        int cod = controladorContrato.cargarCodigo();
        txtNumero.setText(String.valueOf(cod));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtSitio = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        JDateE = new com.toedter.calendar.JDateChooser();
        JDateS = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        cbxEstado = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        btnCrearContrato = new javax.swing.JButton();
        btnBuscarContrato = new javax.swing.JButton();
        btnTerminarContrato = new javax.swing.JButton();
        btnCalcularValor = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setClosable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel7.setText("Cedula");

        jLabel8.setText("Sitio de Parqueo");

        jLabel2.setText("Numero de Contrato");

        jLabel3.setText("Fecha de Entrada");

        txtNombre.setEditable(false);
        txtNombre.setBackground(new java.awt.Color(255, 255, 204));

        jLabel4.setText("Fecha de Salida");

        txtApellido.setEditable(false);
        txtApellido.setBackground(new java.awt.Color(255, 255, 204));

        jLabel5.setText("Nombre Cliente");

        txtCedula.setEditable(false);
        txtCedula.setBackground(new java.awt.Color(255, 255, 204));

        jLabel6.setText("Apellido");

        jLabel1.setText("Placa del vehiculo");

        JDateE.setDateFormatString("y MMM d HH:mm:ss");

        JDateS.setDateFormatString("y MMM d HH:mm:ss");

        jLabel9.setText("Estado");

        cbxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "pagado", "no pagado" }));

        jLabel10.setText("Total a Pagar");

        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscra Vehiculo");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel11.setText("Borre el numero solo en caso de busqueda del contrato");

        btnCrearContrato.setText("Crear Contrato");
        btnCrearContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearContratoActionPerformed(evt);
            }
        });

        btnBuscarContrato.setText("Buscar Contrato");
        btnBuscarContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarContratoActionPerformed(evt);
            }
        });

        btnTerminarContrato.setText("Terminar Contrato");
        btnTerminarContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerminarContratoActionPerformed(evt);
            }
        });

        btnCalcularValor.setText("Calcular valor");
        btnCalcularValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularValorActionPerformed(evt);
            }
        });

        jLabel12.setText("Contrato por dia:$ 15 ");

        jLabel13.setText("Contrato por semana:$ 50 ");

        jLabel14.setText("Contrato por mes:$ 90");

        jLabel15.setText("Contratos no superior a un mes ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8))
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbxEstado, 0, 158, Short.MAX_VALUE)
                            .addComponent(txtSitio, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNombre)
                            .addComponent(txtApellido)
                            .addComponent(txtCedula)
                            .addComponent(txtTotal)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(btnCrearContrato))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBuscarContrato)
                                .addGap(41, 41, 41)
                                .addComponent(btnTerminarContrato))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(jLabel11))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtPlaca, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JDateS, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(JDateE, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnCalcularValor)
                                    .addComponent(btnBuscar)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15))))))
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addGap(32, 32, 32))
                            .addComponent(JDateE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(JDateS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscar)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtSitio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cbxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalcularValor))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearContrato)
                    .addComponent(btnBuscarContrato)
                    .addComponent(btnTerminarContrato))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        
        String palaca= txtPlaca.getText();
        Vehiculo v = new Vehiculo(palaca);
        Vehiculo vehiculo = controladorVehiculo.read(v);
        if(vehiculo!= null){
            Cliente cliente= vehiculo.getCliente();
            txtNombre.setText(cliente.getNombre());
            txtApellido.setText(cliente.getApellido());
            txtCedula.setText(cliente.getCedula());
        }else{
            int opcion=JOptionPane.showConfirmDialog(this, "Vehiculo no encontrado desea crear uno"); 
            if(opcion== JOptionPane.YES_OPTION)
            {
                ventanaPrincipal.getDesktopPane().add(ventanaGestionVehiculo);
                ventanaGestionVehiculo.setVisible(true);
            }
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        cargarCodigo();
        btnTerminarContrato.setEnabled(false);
        Calendar fechaEntrada= Calendar.getInstance();
        JDateE.setCalendar(fechaEntrada);
    }//GEN-LAST:event_formInternalFrameActivated

    private void btnCrearContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearContratoActionPerformed
        boolean resultado = false;
        int codigo=Integer.parseInt(txtNumero.getText());
        Calendar fechaEntrada = JDateE.getCalendar();
        Calendar fechaSalida = JDateS.getCalendar();
        String palaca= txtPlaca.getText();
        Vehiculo v = new Vehiculo(palaca);
        Vehiculo vehiculo = controladorVehiculo.read(v);
        Cliente cliente= vehiculo.getCliente();
        String numero=txtSitio.getText();
        String estado=(String) cbxEstado.getSelectedItem();
        
        String tv=txtTotal.getText();
        double total=Double.parseDouble(txtTotal.getText());
        
        Sitio sit = new Sitio(numero);
        
        Contrato con =new Contrato(codigo);
        if(palaca.isEmpty()||estado.isEmpty()||numero.isEmpty()||tv.isEmpty()){
            JOptionPane.showMessageDialog(this, "Llene todos los campos solicitados");
        }else{
            if(controladorContrato.read(con)!=null){
                JOptionPane.showMessageDialog(this, "Contrato ya creado con este numero");
            }else{
                Sitio siti=controladorSitio.read(sit);
                if(siti!= null){
                    if(siti.getEstado().equals("Libre")){
                        Sitio sitio= new Sitio(numero,"Contrato", vehiculo);
                        controladorSitio.update(sitio);
                        if(estado.equals("pagado")){
                            Contrato contrato= new Contrato(codigo, cliente, sitio, fechaEntrada, fechaSalida, estado, 0);
                            controladorContrato.create(contrato);
                        }else{
                            Contrato contrato= new Contrato(codigo, cliente, sitio, fechaEntrada, fechaSalida, estado, total);
                            controladorContrato.create(contrato);
                        }   
                    }else{
                        JOptionPane.showMessageDialog(this, "El sitio indicado esta ocupado");
                    }
                } else {
                    Sitio sitio = new Sitio(numero, "Contrato", vehiculo);
                    controladorSitio.create(sitio);
                    if (estado.equals("pagado")) {
                        Contrato contrato = new Contrato(codigo, cliente, sitio, fechaEntrada, fechaSalida, estado, 0);
                        controladorContrato.create(contrato);
                    } else {
                        Contrato contrato = new Contrato(codigo, cliente, sitio, fechaEntrada, fechaSalida, estado, total);
                        controladorContrato.create(contrato);
                    }
                }
            }
            JOptionPane.showMessageDialog(this, "Gracias por adquirir un contrato");
            this.setVisible(false);
            limpiar();
            
            
        }
    }//GEN-LAST:event_btnCrearContratoActionPerformed

    private void btnBuscarContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarContratoActionPerformed
        int codigo=Integer.parseInt(txtNumero.getText());
        Contrato con =new Contrato(codigo);
        Contrato contrato= controladorContrato.read(con);
        if(contrato!=null){
            JDateE.setCalendar(contrato.getFechaInicio());
            JDateS.setCalendar(contrato.getFechaFinal());
            Sitio sitio= contrato.getSitio();
            Vehiculo vehiculo = sitio.getVehiculo();
            txtPlaca.setText(vehiculo.getPlaca());
            txtNombre.setText(contrato.getCliente().getNombre());
            txtApellido.setText(contrato.getCliente().getApellido());
            txtCedula.setText(contrato.getCliente().getCedula());
            txtTotal.setText(String.valueOf(contrato.getValorAPagar()));
            txtSitio.setText(sitio.getNumero());
            cbxEstado.setSelectedItem(contrato.getEstadoPago());
            btnBuscar.setEnabled(false);
            btnCrearContrato.setEnabled(false);
            btnCalcularValor.setEnabled(false);
            btnTerminarContrato.setEnabled(true);
        }else{
            JOptionPane.showMessageDialog(this, "No se  encantrado un contrato con este numero");
        }
    }//GEN-LAST:event_btnBuscarContratoActionPerformed

    private void btnTerminarContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerminarContratoActionPerformed

        int numero=Integer.parseInt(txtNumero.getText());
        double total=0.0;
        Contrato con= new Contrato(numero);
        Contrato contrato= controladorContrato.read(con);
        if(contrato.getFechaFinal().before(Calendar.getInstance())){
            if(contrato.getEstadoPago().equals("no pagado")){
                total=contrato.getValorAPagar()+(contrato.getValorAPagar()*0.10);           
            }
        }
        
        txtTotal.setText(String.valueOf(total));
        Cliente cliente = contrato.getCliente();
        Sitio sitio= contrato.getSitio();
        
        JOptionPane.showMessageDialog(this, "Gracias vuelva pronto valor a cancelar"+txtTotal.getText());
        Sitio sitios= new Sitio(txtSitio.getText(), "Libre", null);
        controladorSitio.update(sitios);
        
        
        Contrato contrato1= new Contrato(numero, cliente, sitio, contrato.getFechaInicio(), contrato.getFechaFinal(),"pagado", 0);
        controladorContrato.update(contrato1);
        
        limpiar();
        
        btnCrearContrato.setEnabled(true);
        btnBuscar.setEnabled(true);
        btnCalcularValor.setEnabled(true);
        btnTerminarContrato.setEnabled(false);
        this.setVisible(false);
        limpiar();
    }//GEN-LAST:event_btnTerminarContratoActionPerformed

    private void btnCalcularValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularValorActionPerformed
        long DiferenciaMiliSegundos= Math.abs(JDateS.getCalendar().getTimeInMillis()-JDateE.getCalendar().getTimeInMillis());
        long dias=TimeUnit.MILLISECONDS.toDays(DiferenciaMiliSegundos);
        
        if(dias<=7){
            int valorPagar=(int)(dias*15);
            txtTotal.setText(String.valueOf(valorPagar));
        }else{
            if(dias<=24){
                double numerose= dias/8;
                if(numerose==1.0){
                    int valorPagar=(int)(1*50);
                    txtTotal.setText(String.valueOf(valorPagar));
                }else
                if(numerose<=2.0){
                    int valorPagar=(int)(2*50);
                    txtTotal.setText(String.valueOf(valorPagar));
                }else
                if(numerose<=3.0){
                    int valorPagar=(int)(3*50);
                    txtTotal.setText(String.valueOf(valorPagar));
                }
            }else{
                if(dias<=30.0||dias==31.0){
                    int valorPagar=(int)(1*90);
                    txtTotal.setText(String.valueOf(valorPagar));
                }else{
                    JOptionPane.showMessageDialog(this, "Contratos maximos por un mes");
                    txtTotal.setText("");
                }
            }
            
        }
        System.out.println(dias);
        
    }//GEN-LAST:event_btnCalcularValorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser JDateE;
    private com.toedter.calendar.JDateChooser JDateS;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscarContrato;
    private javax.swing.JButton btnCalcularValor;
    private javax.swing.JButton btnCrearContrato;
    private javax.swing.JButton btnTerminarContrato;
    private javax.swing.JComboBox<String> cbxEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtPlaca;
    private javax.swing.JTextField txtSitio;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables

    private void limpiar() {
        txtPlaca.setText("");
        txtNombre.setText("");
        txtApellido.setText("");
        txtCedula.setText("");
        txtTotal.setText("");
        txtSitio.setText("");
        cbxEstado.setSelectedIndex(0);
        //JDateE.setDateFormatString("");
        JDateS.setDateFormatString("");
    }
}
