/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import javax.swing.JOptionPane;


/**
 *
 * @author NANCY
 */
public class VentanaCrearSitios extends javax.swing.JInternalFrame {

    private VentanaSitios ventanaSitios;
    private int contador=0;
    /**
     * Creates new form VentanaCrearSitios
     */
    public VentanaCrearSitios(VentanaSitios ventanaSitios) {
        initComponents();
        this.ventanaSitios=ventanaSitios;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAbrir = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setClosable(true);

        btnAbrir.setText("Abrir nuevo Sitio");
        btnAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar Sitio");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(btnAbrir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(btnEliminar)
                .addGap(65, 65, 65))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAbrir)
                    .addComponent(btnEliminar))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirActionPerformed
        if(contador<=10){
            contador++;
            if(contador==1){
                ventanaSitios.getBtn51().setVisible(true);
                ventanaSitios.getTxt51().setVisible(true);
            }
            if(contador==2){
                ventanaSitios.getBtn52().setVisible(true);
                ventanaSitios.getTxt52().setVisible(true);
            }
            if(contador==3){
                ventanaSitios.getBtn53().setVisible(true);
                ventanaSitios.getTxt53().setVisible(true);
            }
            if(contador==4){
                ventanaSitios.getBtn54().setVisible(true);
                ventanaSitios.getTxt54().setVisible(true);
            }
            if(contador==5){
                ventanaSitios.getBtn55().setVisible(true);
                ventanaSitios.getTxt55().setVisible(true);
            }
            if(contador==6){
                ventanaSitios.getBtn56().setVisible(true);
                ventanaSitios.getTxt56().setVisible(true);
            }
            if(contador==7){
                ventanaSitios.getBtn57().setVisible(true);
                ventanaSitios.getTxt57().setVisible(true);
            }
            if(contador==8){
                ventanaSitios.getBtn58().setVisible(true);
                ventanaSitios.getTxt58().setVisible(true);
            }
            if(contador==9){
                ventanaSitios.getBtn59().setVisible(true);
                ventanaSitios.getTxt59().setVisible(true);
            }
             if(contador==10){
                ventanaSitios.getBtn60().setVisible(true);
                ventanaSitios.getTxt60().setVisible(true);
            }
        }else{
            JOptionPane.showMessageDialog(this, "No se pueden abrir mas sitios no hay mas espacio");
        }
    }//GEN-LAST:event_btnAbrirActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if(contador>0){
            
            if(contador==1){
                ventanaSitios.getBtn51().setVisible(false);
                ventanaSitios.getTxt51().setVisible(false);
            }
            if(contador==2){
                ventanaSitios.getBtn52().setVisible(false);
                ventanaSitios.getTxt52().setVisible(false);
            }
            if(contador==3){
                ventanaSitios.getBtn53().setVisible(false);
                ventanaSitios.getTxt53().setVisible(false);
            }
            if(contador==4){
                ventanaSitios.getBtn54().setVisible(false);
                ventanaSitios.getTxt54().setVisible(false);
            }
            if(contador==5){
                ventanaSitios.getBtn55().setVisible(false);
                ventanaSitios.getTxt55().setVisible(false);
            }
            if(contador==6){
                ventanaSitios.getBtn56().setVisible(false);
                ventanaSitios.getTxt56().setVisible(false);
            }
            if(contador==7){
                ventanaSitios.getBtn57().setVisible(false);
                ventanaSitios.getTxt57().setVisible(false);
            }
            if(contador==8){
                ventanaSitios.getBtn58().setVisible(false);
                ventanaSitios.getTxt58().setVisible(false);
            }
            if(contador==9){
                ventanaSitios.getBtn59().setVisible(false);
                ventanaSitios.getTxt59().setVisible(false);
            }
             if(contador==10){
                ventanaSitios.getBtn60().setVisible(false);
                ventanaSitios.getTxt60().setVisible(false);
            }
            contador--;
        }else{
            JOptionPane.showMessageDialog(this, "No se pueden eliminar mas sitios");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrir;
    private javax.swing.JButton btnEliminar;
    // End of variables declaration//GEN-END:variables
}
